name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Validar construcción de la imagen Nginx
        run: docker build -t front-tics:latest .

  cd:
    name: Deploy
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Despliegue automático
        run: echo 

    steps:
      - name: Despliegue automático
        run: |
          
